name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Choose Terraform action'
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'apply'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t oseghale1/flask-app:latest ./application
          docker push oseghale1/flask-app:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.3

      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform Configuration
        run: terraform fmt

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Run Terraform Action
        run: terraform ${{ github.event.inputs.action }} -auto-approve -input=false
